name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
       
    - name: Set up Docker 
      uses: docker/setup-docker@v2
      with: 
        dockerfile: Dockerfile
        context: .
          
    - name: Build the Docker image
      run: docker build -t kennynuga/jully:latest .
    
    - name: Login to Docker Hub
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}} 
      
    - name: Push the Docker image
      run: docker push kennynuga/jully:latest
        

   
    
    
