name: Publish Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps: 
      - name: checkout the repo
        uses: actions/checkout@v2
        
      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          image: kennynuga/jully .,kennynuga/amazon .
          registry: docker.io
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}} 
        
      - name: build docker images
        uses: docker/build-action@v4
        with:
          push: true
          tags: user/app:latest
          
      - name: push docker images
        uses: docker/push-action@v5
        with:
          push: true
          tags: user/app:latest
          
        

   
    
    
