name: Publish Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps: 
      - name: checkout the repo
        uses: actions/checkout@v3
        
      - name: login to Docker Hub
        with:
          image: kennynuga/jully .
          registry: docker.io
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}} 
        
      - name: build docker images
        run: docker build -t kennynuga/jully .

      - name: push docker images
        run: docker push kennynuga/jully:latest

   
    
    
